# -*- coding: utf-8 -*-
"""MODELS_422.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tVrtXwciYJCZQWMW4HxFW9IVfjsd1TXL
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

dataset=pd.read_csv("/content/1.csv")

dataset

dataset.head(16)

print ('Shape of the dataset is {}. This dataset contains {} rows and {} columns.'.format(dataset.shape,dataset.shape[0],dataset.shape[1]))

dataset.info()

"""DATA SPLITING

"""

##Selecting numerical features
numerical_data = dataset.select_dtypes(include='number')

#append the features of numerical_data to list
numerical_features=numerical_data.columns.tolist()

print(f'There are {len(numerical_features)} numerical features:', '\n')
print(numerical_features)

#Selecting categoricalfeatures
categorical_data=dataset.select_dtypes(include= 'object')

#append the features of categorical_data to list
categorical_features=categorical_data.columns.tolist()

print(f'There are {len(categorical_features)} numerical features:', '\n')
print(categorical_features)

"""DESCRIPTIVE ANALYSIS


"""

# Transposed stats for numerical features

numerical_data.describe().T

# Transposed stats for categorical features

categorical_data.describe().T

numerical_data.var()

"""SKEWNESS"""

numerical_data.skew()

"""HISTOGRAM and BOX PLOTTING

"""

numerical_data.hist(figsize=(12,12),bins=20)
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# Select only numerical columns for boxplot analysis
numeric_cols = dataset.select_dtypes(include=['int64', 'float64']).columns

# Set up the figure
plt.figure(figsize=(20, 30))

# Plot boxplots for each numerical feature including the target variable 'OUTCOME'
for i, col in enumerate(numeric_cols, 1):
    plt.subplot(len(numeric_cols), 1, i)
    sns.boxplot(x=dataset[col], color='skyblue')
    plt.title(f'Boxplot of {col}', fontsize=12)
    plt.tight_layout()

plt.show()

"""UNIQUE VALUES in EACH FEATURE

"""

numerical_data.nunique()

"""MISSING VALUES

"""

numerical_data.isnull().sum()

"""NUMBER OF UNIQUE VALUES IN CATEGORICAL FEATURE

"""

# unique values counts
unique_counts=categorical_data.nunique()
print(unique_counts)

"""MISSING DATA HANDLING

"""

# Check missing values
missing_values = df.isnull().sum()

# Percentage of missing values
missing_percentage = (df.isnull().sum() / len(df)) * 100

missing_summary = pd.DataFrame({
    'Missing Values': missing_values,
    'Percentage (%)': missing_percentage
})

missing_summary = missing_summary[missing_summary['Missing Values'] > 0]

missing_summary

# Create a copy of the original dataset
df_clean = df.copy()

# Check the missing values before handling them
print("Missing values before preprocessing:")
print(df_clean.isnull().sum())

# Fill numerical missing values with median
df_clean['BMI'] = df_clean['BMI'].fillna(df_clean['BMI'].median())
df_clean['Cholesterol'] = df_clean['Cholesterol'].fillna(
    df_clean['Cholesterol'].median()
)

# Fill missing Smoking_Habit values with the most frequent category
df_clean['Smoking_Habit'] = df_clean['Smoking_Habit'].fillna(
    df_clean['Smoking_Habit'].mode()[0]
)

# Re-create Smoking_Binary after handling missing Smoking_Habit
df_clean['Smoking_Binary'] = df_clean['Smoking_Habit'].map({
    'Non-Smoker': 0,
    'Smoker': 1
})

"""MISSING VALUES AFTER EDA and PREPROCESSING
**bold text**
"""

print("Missing values after preprocessing:")
print(df_clean.isnull().sum())

"""CHECK FOR DUPLICATE VALUES

"""

print("Duplicate rows:", df_clean.duplicated().sum())
print(df_clean.isnull().sum())

"""### **Barplot of unique value counts in every categorical features**"""

for col in categorical_features:
    plt.title(f'Distribution of {col}')
    categorical_data[col].value_counts().sort_index().plot(kind='bar', rot=0, xlabel=col,ylabel='count')
    plt.show()

"""**CORRELATION ANALYSIS**"""

# Calculate the correlation matrix
correlation_matrix = numerical_data.corr()
correlation_matrix

"""CORRELATION HEATMAP OF THE WHOLE DATASET"""

# Plotting the heatmap for correlation matrix
plt.figure(figsize=(8, 6))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt='.3f', linewidths=0.3)
plt.show()

from scipy.stats import chi2_contingency
import numpy as np



import pandas as pd

df = pd.read_csv('1.csv')

df.head()

import matplotlib.pyplot as plt
import seaborn as sns

# Select numerical columns
numerical_cols = [
    'Age',
    'BMI',
    'Blood_Pressure',
    'Cholesterol',
    'Heart_Rate'
]

numerical_data = df[numerical_cols]

# Create 3 plots
fig, ax = plt.subplots(3, 1, figsize=(10, 15))

# Pearson
corr_pearson = numerical_data.corr(method='pearson')

# Spearman
corr_spearman = numerical_data.corr(method='spearman')

# Kendall
corr_kendall = numerical_data.corr(method='kendall')

# Heatmaps
sns.heatmap(
    corr_pearson,
    ax=ax[0],
    annot=True,
    fmt='.2f',
    cmap='coolwarm'
)
ax[0].set_title('Pearson Correlation')

sns.heatmap(
    corr_spearman,
    ax=ax[1],
    annot=True,
    fmt='.2f',
    cmap='coolwarm'
)
ax[1].set_title('Spearman Rank Correlation')

sns.heatmap(
    corr_kendall,
    ax=ax[2],
    annot=True,
    fmt='.2f',
    cmap='coolwarm'
)
ax[2].set_title("Kendall's Tau Correlation")

plt.tight_layout()
plt.show()

from scipy.stats import chi2_contingency
import numpy as np

def cramers_v(x, y):
    confusion_matrix = pd.crosstab(x, y)

    chi2 = chi2_contingency(confusion_matrix)[0]

    n = confusion_matrix.sum().sum()

    phi2 = chi2 / n

    r, k = confusion_matrix.shape

    phi2corr = max(
        0,
        phi2 - ((k - 1) * (r - 1)) / (n - 1)
    )

    rcorr = r - ((r - 1) ** 2) / (n - 1)
    kcorr = k - ((k - 1) ** 2) / (n - 1)

    return np.sqrt(
        phi2corr / min(kcorr - 1, rcorr - 1)
    )

categorical_cols = [
    'Smoking_Habit',
    'Physical_Activity_Level',
    'Family_History',
    'Disease_Type'
]

cramers_matrix = pd.DataFrame(
    index=categorical_cols,
    columns=categorical_cols,
    dtype=float
)

for col1 in categorical_cols:
    for col2 in categorical_cols:
        cramers_matrix.loc[col1, col2] = cramers_v(
            df[col1],
            df[col2]
        )

print(cramers_matrix)

plt.figure(figsize=(9, 7))

sns.heatmap(
    cramers_matrix,
    annot=True,
    fmt='.2f',
    cmap='coolwarm',
    vmin=0,
    vmax=1
)

plt.title("Cramér's V - Categorical Variables")
plt.tight_layout()
plt.show()

df['Smoking_Binary'] = df['Smoking_Habit'].map({
    'Non-Smoker': 0,
    'Smoker': 1
})

from scipy.stats import pointbiserialr

numerical_cols = [
    'Age',
    'BMI',
    'Blood_Pressure',
    'Cholesterol',
    'Heart_Rate'
]

smoking_results = {}

for col in numerical_cols:
    r, p = pointbiserialr(
        df['Smoking_Binary'],
        df[col]
    )

    smoking_results[col] = {
        'Correlation': r,
        'P-value': p
    }

smoking_results_df = pd.DataFrame(smoking_results).T

print(smoking_results_df)

df['Family_History_Binary'] = df['Family_History'].map({
    'No': 0,
    'Yes': 1
})

family_results = {}

for col in numerical_cols:
    r, p = pointbiserialr(
        df['Family_History_Binary'],
        df[col]
    )

    family_results[col] = {
        'Correlation': r,
        'P-value': p
    }

family_results_df = pd.DataFrame(family_results).T

print(family_results_df)

point_biserial_matrix = pd.DataFrame({
    'Smoking_Habit': smoking_results_df['Correlation'],
    'Family_History': family_results_df['Correlation']
})

plt.figure(figsize=(8, 6))

sns.heatmap(
    point_biserial_matrix,
    annot=True,
    fmt='.2f',
    cmap='coolwarm',
    center=0
)

plt.title('Point-Biserial Correlation')
plt.xlabel('Binary Variables')
plt.ylabel('Numerical Variables')

plt.tight_layout()
plt.show()

df['Physical_Activity_Ordinal'] = df[
    'Physical_Activity_Level'
].map({
    'Low': 1,
    'Moderate': 2,
    'High': 3
})

activity_spearman = {}

for col in numerical_cols:
    correlation = df[[col, 'Physical_Activity_Ordinal']].corr(
        method='spearman'
    ).iloc[0, 1]

    activity_spearman[col] = correlation

print("Spearman:")
print(pd.Series(activity_spearman))

activity_kendall = {}

for col in numerical_cols:
    correlation = df[[col, 'Physical_Activity_Ordinal']].corr(
        method='kendall'
    ).iloc[0, 1]

    activity_kendall[col] = correlation

print("Kendall:")
print(pd.Series(activity_kendall))

# Disease Type distribution

outcome_counts = df['Disease_Type'].value_counts()
outcome_percentages = df['Disease_Type'].value_counts(normalize=True) * 100

plt.figure(figsize=(8, 5))

ax = sns.barplot(
    x=outcome_counts.index,
    y=outcome_counts.values
)

plt.title('Distribution of Disease Types')
plt.xlabel('Disease Type')
plt.ylabel('Number of Samples')

# Add count and percentage labels
for i, (count, percentage) in enumerate(
    zip(outcome_counts.values, outcome_percentages.values)
):
    ax.text(
        i,
        count + 10,
        f'{count} ({percentage:.2f}%)',
        ha='center'
    )

plt.show()

# Percentage distribution of Disease Type

percentage_df = pd.DataFrame({
    'Disease Type': outcome_percentages.index,
    'Percentage': outcome_percentages.values
})

percentage_df

numerical_cols = [
    'Age',
    'BMI',
    'Blood_Pressure',
    'Cholesterol',
    'Heart_Rate'
]

for col in numerical_cols:

    plt.figure(figsize=(8, 5))

    sns.kdeplot(
        data=df,
        x=col,
        hue='Disease_Type',
        fill=True,
        common_norm=False
    )

    plt.title(f'Density Plot of {col} by Disease Type')
    plt.xlabel(col)
    plt.ylabel('Density')

    plt.show()

"""SCALING AND TEST/SPLIT

"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, label_binarize

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.cluster import KMeans

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    roc_curve,
    auc,
    roc_auc_score
)

from scipy.optimize import linear_sum_assignment

# Make a copy
model_data = dataset.copy()

# Fill missing numerical values
model_data['BMI'] = model_data['BMI'].fillna(model_data['BMI'].median())
model_data['Cholesterol'] = model_data['Cholesterol'].fillna(
    model_data['Cholesterol'].median()
)

# Fill missing categorical values
model_data['Smoking_Habit'] = model_data['Smoking_Habit'].fillna(
    model_data['Smoking_Habit'].mode()[0]
)

# Convert categorical features into numerical values
model_data = pd.get_dummies(
    model_data,
    columns=[
        'Smoking_Habit',
        'Physical_Activity_Level',
        'Family_History'
    ],
    drop_first=True
)

model_data.head()

# Features
X = model_data.drop('Disease_Type', axis=1)

# Target
y = model_data['Disease_Type']

print("X shape:", X.shape)
print("y shape:", y.shape)

print("\nClasses:")
print(y.unique())

from sklearn.preprocessing import LabelEncoder

# Encode Disease_Type
label_encoder = LabelEncoder()

y_encoded = label_encoder.fit_transform(y)

print("Class mapping:")
for i, class_name in enumerate(label_encoder.classes_):
    print(i, "=", class_name)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y_encoded,
    test_size=0.30,
    random_state=42,
    stratify=y_encoded
)

print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("Scaling completed.")

"""LOGISTIC REGRESSION"""

log_model = LogisticRegression(max_iter=5000)

log_model.fit(X_train_scaled, y_train)

y_pred_log = log_model.predict(X_test_scaled)
y_prob_log = log_model.predict_proba(X_test_scaled)

print("Logistic Regression trained.")

"""Logistic Regression Accuracy"""

log_accuracy = accuracy_score(y_test, y_pred_log)

print("Logistic Regression Accuracy:", log_accuracy)

print("\nClassification Report:")
print(
    classification_report(
        y_test,
        y_pred_log,
        target_names=label_encoder.classes_
    )
)

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

# Logistic Regression Metrics

log_accuracy = accuracy_score(y_test, y_pred_log)

log_precision = precision_score(
    y_test,
    y_pred_log,
    average='weighted'
)

log_recall = recall_score(
    y_test,
    y_pred_log,
    average='weighted'
)

log_f1 = f1_score(
    y_test,
    y_pred_log,
    average='weighted'
)

print("===== Logistic Regression Evaluation =====")
print(f"Accuracy : {log_accuracy:.4f}")
print(f"Precision: {log_precision:.4f}")
print(f"Recall   : {log_recall:.4f}")
print(f"F1 Score : {log_f1:.4f}")

print("\nClassification Report:")
print(
    classification_report(
        y_test,
        y_pred_log,
        target_names=label_encoder.classes_
    )
)

""" Logistic Regression Confusion Matrix"""

cm_log = confusion_matrix(
    y_test,
    y_pred_log
)

plt.figure(figsize=(7, 5))

sns.heatmap(
    cm_log,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=label_encoder.classes_,
    yticklabels=label_encoder.classes_
)

plt.xlabel("Predicted Label")
plt.ylabel("Actual Label")
plt.title("Logistic Regression - Confusion Matrix")

plt.show()

plt.figure(figsize=(8, 6))

for i in range(3):
    plt.plot(
        fpr_log[i],
        tpr_log[i],
        label=f"{label_encoder.classes_[i]} (AUC = {auc_log[i]:.2f})"
    )

plt.plot([0, 1], [0, 1], 'k--')

plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("Logistic Regression - ROC Curve")
plt.legend()
plt.grid()

plt.show()

"""RANDOM FOREST"""

rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)
rf_model.fit(X_train, y_train)

y_pred_rf = rf_model.predict(X_test)
y_prob_rf = rf_model.predict_proba(X_test)

print("Random Forest trained.")

"""Random Forest Evaluation

"""

# Random Forest Metrics

rf_accuracy = accuracy_score(
    y_test,
    y_pred_rf
)

rf_precision = precision_score(
    y_test,
    y_pred_rf,
    average='weighted'
)

rf_recall = recall_score(
    y_test,
    y_pred_rf,
    average='weighted'
)

rf_f1 = f1_score(
    y_test,
    y_pred_rf,
    average='weighted'
)

print("===== Random Forest Evaluation =====")
print(f"Accuracy : {rf_accuracy:.4f}")
print(f"Precision: {rf_precision:.4f}")
print(f"Recall   : {rf_recall:.4f}")
print(f"F1 Score : {rf_f1:.4f}")

print("\nClassification Report:")
print(
    classification_report(
        y_test,
        y_pred_rf,
        target_names=label_encoder.classes_
    )
)

"""#Random Forest Confusion Matrix

"""

cm_rf = confusion_matrix(
    y_test,
    y_pred_rf
)

plt.figure(figsize=(7, 5))

sns.heatmap(
    cm_rf,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=label_encoder.classes_,
    yticklabels=label_encoder.classes_
)

plt.xlabel("Predicted Label")
plt.ylabel("Actual Label")
plt.title("Random Forest - Confusion Matrix")

plt.show()

"""RANDOM FOREST AUC"""

fpr_rf = {}
tpr_rf = {}
auc_rf = {}

for i in range(3):

    fpr_rf[i], tpr_rf[i], _ = roc_curve(
        y_test_bin[:, i],
        y_prob_rf[:, i]
    )

    auc_rf[i] = auc(
        fpr_rf[i],
        tpr_rf[i]
    )

print("Random Forest AUC:")

for i in range(3):
    print(
        label_encoder.classes_[i],
        ":",
        round(auc_rf[i], 4)
    )

rf_macro_auc = roc_auc_score(
    y_test_bin,
    y_prob_rf,
    multi_class='ovr',
    average='macro'
)

print("\nMacro AUC:", round(rf_macro_auc, 4))

"""ROC CURVE RANDOM FOREST

"""

plt.figure(figsize=(8, 6))

for i in range(3):
    plt.plot(
        fpr_rf[i],
        tpr_rf[i],
        label=f"{label_encoder.classes_[i]} (AUC = {auc_rf[i]:.2f})"
    )

plt.plot([0, 1], [0, 1], 'k--')

plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("Random Forest - ROC Curve")
plt.legend()
plt.grid()

plt.show()

# Random Forest Feature Importance

feature_importance = pd.DataFrame({
    'Feature': X_train.columns,
    'Importance': rf_model.feature_importances_
})

feature_importance = feature_importance.sort_values(
    by='Importance',
    ascending=False
)

print(feature_importance)

plt.figure(figsize=(8, 5))

sns.barplot(
    data=feature_importance,
    x='Importance',
    y='Feature'
)

plt.title("Random Forest Feature Importance")
plt.xlabel("Importance")
plt.ylabel("Feature")

plt.show()

"""MLP"""

from sklearn.neural_network import MLPClassifier

mlp_model = MLPClassifier(
    hidden_layer_sizes=(64, 32),
    activation='relu',
    solver='adam',
    max_iter=1000,
    random_state=42,
    early_stopping=True
)

mlp_model.fit(X_train_scaled, y_train)

print("MLP trained successfully.")

y_pred_mlp = mlp_model.predict(X_test_scaled)

y_prob_mlp = mlp_model.predict_proba(X_test_scaled)

print("MLP predictions generated.")

"""**Accuracy, Precision, Recall and F1 (MLP)**"""

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report
)

mlp_accuracy = accuracy_score(
    y_test,
    y_pred_mlp
)

mlp_precision = precision_score(
    y_test,
    y_pred_mlp,
    average='weighted'
)

mlp_recall = recall_score(
    y_test,
    y_pred_mlp,
    average='weighted'
)

mlp_f1 = f1_score(
    y_test,
    y_pred_mlp,
    average='weighted'
)

print("===== MLP Evaluation =====")
print(f"Accuracy : {mlp_accuracy:.4f}")
print(f"Precision: {mlp_precision:.4f}")
print(f"Recall   : {mlp_recall:.4f}")
print(f"F1 Score : {mlp_f1:.4f}")

print("\nClassification Report:")
print(
    classification_report(
        y_test,
        y_pred_mlp,
        target_names=label_encoder.classes_
    )
)

from sklearn.metrics import confusion_matrix

cm_mlp = confusion_matrix(
    y_test,
    y_pred_mlp
)

plt.figure(figsize=(7, 5))

sns.heatmap(
    cm_mlp,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=label_encoder.classes_,
    yticklabels=label_encoder.classes_
)

plt.xlabel("Predicted Label")
plt.ylabel("Actual Label")
plt.title("MLP - Confusion Matrix")

plt.show()

from sklearn.preprocessing import label_binarize
from sklearn.metrics import roc_curve, auc, roc_auc_score

classes = label_encoder.classes_

y_test_bin = label_binarize(
    y_test,
    classes=range(len(classes))
)

fpr_mlp = {}
tpr_mlp = {}
auc_mlp = {}

for i in range(len(classes)):
    fpr_mlp[i], tpr_mlp[i], _ = roc_curve(
        y_test_bin[:, i],
        y_prob_mlp[:, i]
    )

    auc_mlp[i] = auc(
        fpr_mlp[i],
        tpr_mlp[i]
    )

"""ROC CURVE (MLP)"""

plt.figure(figsize=(8, 6))

for i, class_name in enumerate(classes):
    plt.plot(
        fpr_mlp[i],
        tpr_mlp[i],
        label=f'{class_name} (AUC = {auc_mlp[i]:.3f})'
    )

plt.plot(
    [0, 1],
    [0, 1],
    linestyle='--'
)

plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('MLP - Multiclass ROC Curve')

plt.legend()

plt.show()

mlp_macro_auc = roc_auc_score(
    y_test_bin,
    y_prob_mlp,
    multi_class='ovr',
    average='macro'
)

print(f"MLP Macro AUC: {mlp_macro_auc:.4f}")

"""**SUPERVISED LEARNING RESULT**"""

results = pd.DataFrame({
    'Model': [
        'Logistic Regression',
        'Random Forest',
        'MLP'
    ],
    'Accuracy': [
        log_accuracy,
        rf_accuracy,
        mlp_accuracy
    ],
    'Precision': [
        log_precision,
        rf_precision,
        mlp_precision
    ],
    'Recall': [
        log_recall,
        rf_recall,
        mlp_recall
    ],
    'F1 Score': [
        log_f1,
        rf_f1,
        mlp_f1
    ],
    'Macro AUC': [
        log_macro_auc,
        rf_macro_auc,
        mlp_macro_auc
    ]
})

results

"""**UNSUPERVISED LEARNING  (K MEANS CLUSTERING )**

Features used for K-Means clustering
"""

# Features used for K-Means
kmeans_features = [
    'Age',
    'BMI',
    'Blood_Pressure',
    'Cholesterol',
    'Heart_Rate',
    'Smoking_Binary',
    'Family_History_Binary',
    'Physical_Activity_Ordinal'
]

X_kmeans = df_clean[kmeans_features]

print("K-Means input shape:", X_kmeans.shape)

# =========================
# K-MEANS CLUSTERING
# =========================

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    confusion_matrix,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    silhouette_score,
    roc_curve,
    auc,
    roc_auc_score
)

from scipy.optimize import linear_sum_assignment

# Use the same train/test indices as your supervised models
X_train_kmeans, X_test_kmeans, y_train_kmeans, y_test_kmeans = train_test_split(
    X_kmeans,
    df_clean['Disease_Type'],
    test_size=0.30,
    random_state=42,
    stratify=df_clean['Disease_Type']
)

kmeans_scaler = StandardScaler()

X_train_kmeans_scaled = kmeans_scaler.fit_transform(X_train_kmeans)
X_test_kmeans_scaled = kmeans_scaler.transform(X_test_kmeans)

print("K-Means data scaled successfully.")

# =========================
# ELBOW METHOD
# =========================

inertias = []

K_range = range(2, 11)

for k in K_range:

    model = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=10
    )

    model.fit(X_train_kmeans_scaled)

    inertias.append(model.inertia_)


plt.figure(figsize=(8, 5))

plt.plot(
    K_range,
    inertias,
    marker='o'
)

plt.xlabel("Number of Clusters (K)")
plt.ylabel("Inertia")
plt.title("Elbow Method for K-Means")
plt.grid()

plt.show()

# =========================
# TRAIN K-MEANS
# =========================

kmeans = KMeans(
    n_clusters=2,
    random_state=42,
    n_init=10
)

kmeans.fit(X_train_kmeans_scaled)

cluster_train = kmeans.labels_
cluster_test = kmeans.predict(X_test_kmeans_scaled)

print("K-Means clustering completed.")

# =========================
# SILHOUETTE SCORE
# =========================

silhouette_train = silhouette_score(
    X_train_kmeans_scaled,
    cluster_train
)

silhouette_test = silhouette_score(
    X_test_kmeans_scaled,
    cluster_test
)

print("Training Silhouette Score:", round(silhouette_train, 4))
print("Testing Silhouette Score :", round(silhouette_test, 4))

# =========================
# MAP K-MEANS CLUSTERS TO CLASS LABELS
# =========================

# Use the encoded training labels: 0, 1, 2
cm_train = confusion_matrix(
    y_train,
    cluster_train
)

row_ind, col_ind = linear_sum_assignment(-cm_train)

cluster_mapping = {
    cluster: class_label
    for class_label, cluster in zip(row_ind, col_ind)
}

print("Cluster mapping:")
print(cluster_mapping)

# =========================
# K-MEANS PREDICTED CLASSES
# =========================

y_pred_kmeans = np.array([
    cluster_mapping[cluster]
    for cluster in cluster_test
])

print("K-Means class predictions generated.")

# =========================
# CONFUSION MATRIX
# =========================

cm_kmeans = confusion_matrix(
    y_test,
    y_pred_kmeans
)

plt.figure(figsize=(7, 5))

sns.heatmap(
    cm_kmeans,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=label_encoder.classes_,
    yticklabels=label_encoder.classes_
)

plt.xlabel("Predicted Label")
plt.ylabel("Actual Label")
plt.title("K-Means - Confusion Matrix")

plt.show()

# =========================
# K-MEANS METRICS
# =========================

kmeans_accuracy = accuracy_score(
    y_test,
    y_pred_kmeans
)

kmeans_precision = precision_score(
    y_test,
    y_pred_kmeans,
    average='weighted',
    zero_division=0
)

kmeans_recall = recall_score(
    y_test,
    y_pred_kmeans,
    average='weighted',
    zero_division=0
)

kmeans_f1 = f1_score(
    y_test,
    y_pred_kmeans,
    average='weighted',
    zero_division=0
)

print("===== K-Means Evaluation =====")
print(f"Accuracy : {kmeans_accuracy:.4f}")
print(f"Precision: {kmeans_precision:.4f}")
print(f"Recall   : {kmeans_recall:.4f}")
print(f"F1 Score : {kmeans_f1:.4f}")

# =========================
# BINARIZE TEST LABELS
# =========================

classes = label_encoder.classes_

y_test_bin_kmeans = label_binarize(
    y_test,
    classes=range(len(classes))
)

print("Test labels binarized.")

# =========================
# CLUSTER DISTRIBUTION
# =========================

cluster_counts = pd.Series(
    cluster_test
).value_counts().sort_index()

print("Test Cluster Distribution:")
print(cluster_counts)

plt.figure(figsize=(7, 5))

cluster_counts.plot(
    kind='bar'
)

plt.xlabel("Cluster")
plt.ylabel("Number of Samples")
plt.title("K-Means Cluster Distribution")
plt.xticks(rotation=0)
plt.grid(axis='y')

plt.show()

# =========================
# CLUSTER VS DISEASE TYPE
# =========================

cluster_disease_table = pd.crosstab(
    cluster_test,
    y_test,
    normalize='index'
)

cluster_disease_table.columns = label_encoder.classes_

print("Cluster Composition by Disease Type:")
print(cluster_disease_table.round(3))

cluster_disease_percent = (
    cluster_disease_table * 100
).round(2)

print("\nCluster Composition (%):")
print(cluster_disease_percent)

# ==========================================
# OVERALL MODEL SUMMARY
# ==========================================

overall_results = pd.DataFrame({
    'Model': [
        'Logistic Regression',
        'Random Forest',
        'MLP',
        'K-Means'
    ],
    'Type': [
        'Supervised',
        'Supervised',
        'Supervised',
        'Unsupervised'
    ],
    'Accuracy': [
        log_accuracy,
        rf_accuracy,
        mlp_accuracy,
        np.nan
    ],
    'Precision': [
        log_precision,
        rf_precision,
        mlp_precision,
        np.nan
    ],
    'Recall': [
        log_recall,
        rf_recall,
        mlp_recall,
        np.nan
    ],
    'F1 Score': [
        log_f1,
        rf_f1,
        mlp_f1,
        np.nan
    ],
    'Macro AUC': [
        log_macro_auc,
        rf_macro_auc,
        mlp_macro_auc,
        np.nan
    ],
    'Silhouette Score': [
        np.nan,
        np.nan,
        np.nan,
        final_silhouette
    ]
})

print("===== OVERALL MODEL PERFORMANCE =====")

display(
    overall_results.style
    .format({
        'Accuracy': '{:.4f}',
        'Precision': '{:.4f}',
        'Recall': '{:.4f}',
        'F1 Score': '{:.4f}',
        'Macro AUC': '{:.4f}',
        'Silhouette Score': '{:.4f}'
    })
)

